export const ROUTES = {
  home: "/",
  login: "/login",
  signup: "/signup",
  translate: "/translate",
  dictionary: "/dictionary",
  learn: "/learn",
  favorites: "/favorites",
  history: "/history",
  community: "/community",
  contribution: "/contribution",
  about: "/about",
  contact: "/contact",
  feedback: "/feedback",
  settings: {
    general: "/settings",
    profile: "/settings/profile",
    appearance: "/settings/appearance",
    notifications: "/settings/notifications",
  },
  live_assistance: "/live-assistance",
  privacy: "/privacy-policy",
  notFound: "/404",
};
