export const ROUTES = {
  home: "/",
  translate: "/translate",
  dictionary: "/dictionary",
  summarization: "/summarization",
  academy: "/academy",
  favorites: "/favorites",
  history: "/history",
  community: "/community",
  contribution: "/contribution",
  about: "/about",
  contact: "/contact",
  feedback: "/feedback",
  live_assistance: "/live-assistance",
  notFound: "/404",
};
