import { ICommunityPost } from "@/models/CommunityPost";
import { IDictionary } from "@/models/Dictionary";

// this just for demonstration!
export const dummyDictionaryData: IDictionary[] = [
  {
    id: 2,
    english: "play",
    darija: "l3b",
    type: "verb",
    arabic: "لعب",
    favorite: true,
    verified: true,
    category: "sports",
  },
  {
    id: 3,
    english: "crazy",
    darija: "msti",
    type: "adjective",
    arabic: "مسطي",
    favorite: true,
    verified: true,
    category: "health",
  },
  {
    id: 9,
    english: "forest",
    darija: "ghaba",
    type: "noun",
    arabic: "غابة",
    favorite: true,
    verified: false,
    category: "nature",
  },
  {
    id: 10,
    english: "window",
    darija: "shrjem",
    type: "noun",
    arabic: "شرجم",
    favorite: true,
    verified: true,
    category: "objects",
  },
  {
    id: 11,
    english: "dog",
    darija: "klb",
    type: "noun",
    arabic: "كلب",
    favorite: true,
    verified: true,
    category: "animals",
  },
  {
    id: 12,
    english: "cat",
    darija: "mch",
    type: "noun",
    arabic: "مش",
    favorite: false,
    verified: true,
    category: "animals",
  },
  {
    id: 13,
    english: "donkey",
    darija: "7mar",
    type: "noun",
    arabic: "حمار",
    favorite: false,
    verified: true,
    category: "animals",
  },
  {
    id: 14,
    english: "clothes",
    darija: "7wayj",
    type: "noun",
    arabic: "حوايج",
    favorite: false,
    verified: true,
    category: "clothes",
  },
  {
    id: 15,
    english: "pants",
    darija: "srwal",
    type: "noun",
    arabic: "سروال",
    favorite: false,
    verified: true,
    category: "clothes",
  },
  {
    id: 16,
    english: "shirt",
    darija: "9amija",
    type: "noun",
    arabic: "قميجة",
    favorite: true,
    verified: true,
    category: "clothes",
  },
  {
    id: 17,
    english: "red",
    darija: "7mr",
    type: "noun",
    arabic: "حمر",
    favorite: false,
    verified: true,
    category: "colors",
  },
  {
    id: 18,
    english: "green",
    darija: "5dr",
    type: "noun",
    arabic: "خضر",
    favorite: false,
    verified: true,
    category: "colors",
  },
  {
    id: 19,
    english: "blue",
    darija: "zr9",
    type: "noun",
    arabic: "زرق",
    favorite: false,
    verified: true,
    category: "colors",
  },
  {
    id: 20,
    english: "orange",
    darija: "limouni",
    type: "noun",
    arabic: "ليموني",
    favorite: false,
    verified: false,
    category: "colors",
  },
  {
    id: 21,
    english: "grey",
    darija: "gri",
    type: "noun",
    arabic: "ڭري",
    favorite: false,
    verified: true,
    category: "colors",
  },
  {
    id: 22,
    english: "brown",
    darija: "9hwi",
    type: "noun",
    arabic: "قهوي",
    favorite: false,
    verified: false,
    category: "colors",
  },
  {
    id: 23,
    english: "brown",
    darija: "bonni",
    type: "noun",
    arabic: "بنّي",
    favorite: false,
    verified: true,
    category: "colors",
  },
  {
    id: 24,
    english: "pink",
    darija: "fanidi",
    type: "noun",
    arabic: "فانيدي",
    favorite: false,
    verified: false,
    category: "colors",
  },
  {
    id: 25,
    english: "pink",
    darija: "wardi",
    type: "noun",
    arabic: "وردي",
    favorite: false,
    verified: true,
    category: "colors",
  },
  {
    id: 26,
    english: "shoe",
    darija: "sbbat",
    type: "noun",
    arabic: "سبّاط",
    favorite: false,
    verified: true,
    category: "clothes",
  },
  {
    id: 27,
    english: "socks",
    darija: "t9achr",
    type: "noun",
    arabic: "تقاشر",
    favorite: false,
    verified: false,
    category: "clothes",
  },
  {
    id: 28,
    english: "shorts",
    darija: "chort",
    type: "noun",
    arabic: "شورط",
    favorite: false,
    verified: false,
    category: "clothes",
  },
  {
    id: 29,
    english: "coat",
    darija: "kbbot",
    type: "noun",
    arabic: "كبّوط",
    favorite: false,
    verified: false,
    category: "clothes",
  },
  {
    id: 30,
    english: "tie",
    darija: "grafaTa",
    type: "noun",
    arabic: "ڭرافاطة",
    favorite: false,
    verified: false,
    category: "clothes",
  },
  {
    id: 31,
    english: "hat",
    darija: "Trbouch",
    type: "noun",
    arabic: "طربوش",
    favorite: false,
    verified: false,
    category: "clothes",
  },
  {
    id: 32,
    english: "jacket",
    darija: "tjakiTa",
    type: "noun",
    arabic: "تجاكيطة",
    favorite: false,
    verified: false,
    category: "clothes",
  },
  {
    id: 33,
    english: "skirt",
    darija: "Saya",
    type: "noun",
    arabic: "صايا",
    favorite: false,
    verified: true,
    category: "clothes",
  },
  {
    id: 34,
    english: "underpants",
    darija: "slip",
    type: "noun",
    arabic: "سليپ",
    favorite: false,
    verified: true,
    category: "clothes",
  },
  {
    id: 35,
    english: "scarf",
    darija: "chal",
    type: "noun",
    arabic: "شال",
    favorite: false,
    verified: false,
    category: "clothes",
  },
  {
    id: 36,
    english: "jeans",
    darija: "djin",
    type: "noun",
    arabic: "دجين",
    favorite: false,
    verified: false,
    category: "clothes",
  },
  {
    id: 37,
    english: "giraffe",
    darija: "zarafa",
    type: "noun",
    arabic: "زرافة",
    favorite: false,
    verified: false,
    category: "animals",
  },
  {
    id: 38,
    english: "lion",
    darija: "sb3",
    type: "noun",
    arabic: "سبع",
    favorite: false,
    verified: true,
    category: "animals",
  },
  {
    id: 39,
    english: "chicken",
    darija: "djaja",
    type: "noun",
    arabic: "دجاجة",
    favorite: false,
    verified: true,
    category: "animals",
  },
  {
    id: 40,
    english: "cock",
    darija: "frouj",
    type: "noun",
    arabic: "فروج",
    favorite: false,
    verified: true,
    category: "animals",
  },
  {
    id: 41,
    english: "gazelle",
    darija: "ghzala",
    type: "noun",
    arabic: "غزالة",
    favorite: false,
    verified: true,
    category: "animals",
  },
  {
    id: 42,
    english: "tiger",
    darija: "nmr",
    type: "noun",
    arabic: "نمر",
    favorite: false,
    verified: false,
    category: "animals",
  },
  {
    id: 43,
    english: "hyena",
    darija: "Db3",
    type: "noun",
    arabic: "ضبع",
    favorite: false,
    verified: false,
    category: "animals",
  },
  {
    id: 44,
    english: "fish",
    darija: "7out",
    type: "noun",
    arabic: "حوت",
    favorite: false,
    verified: false,
    category: "animals",
  },
  {
    id: 45,
    english: "teacher",
    darija: "oustad",
    type: "noun",
    arabic: "أستاذ",
    favorite: false,
    verified: true,
    category: "education",
  },
  {
    id: 46,
    english: "student",
    darija: "tlmid",
    type: "noun",
    arabic: "تلميد",
    favorite: false,
    verified: false,
    category: "education",
  },
  {
    id: 47,
    english: "director",
    darija: "moudir",
    type: "noun",
    arabic: "مدير",
    favorite: true,
    verified: false,
    category: "education",
  },
  {
    id: 48,
    english: "dean",
    darija: "3amid",
    type: "noun",
    arabic: "عميد",
    favorite: false,
    verified: false,
    category: "education",
  },
  {
    id: 49,
    english: "blackboard",
    darija: "sbbora",
    type: "noun",
    arabic: "سبّورة",
    favorite: true,
    verified: true,
    category: "education",
  },
  {
    id: 50,
    english: "chalk",
    darija: "Tabachir",
    type: "noun",
    arabic: "طباشير",
    favorite: false,
    verified: false,
    category: "education",
  },
  {
    id: 51,
    english: "physics",
    darija: "fizik",
    type: "noun",
    arabic: "فيزيك",
    favorite: false,
    verified: true,
    category: "education",
  },
  {
    id: 52,
    english: "history",
    darija: "tarikh",
    type: "noun",
    arabic: "تاريخ",
    favorite: false,
    verified: false,
    category: "education",
  },
  {
    id: 53,
    english: "math",
    darija: "ryaDiat",
    type: "noun",
    arabic: "رياضيات",
    favorite: false,
    verified: true,
    category: "education",
  },
  {
    id: 54,
    english: "sports",
    darija: "ryaDa",
    type: "noun",
    arabic: "رياضة",
    favorite: false,
    verified: true,
    category: "education",
  },
  {
    id: 55,
    english: "geography",
    darija: "joghrafia",
    type: "noun",
    arabic: "جغرافيا",
    favorite: false,
    verified: false,
    category: "education",
  },
  {
    id: 56,
    english: "course",
    darija: "drs",
    type: "noun",
    arabic: "درس",
    favorite: false,
    verified: false,
    category: "education",
  },
  {
    id: 57,
    english: "exam",
    darija: "mti7an",
    type: "noun",
    arabic: "متحان",
    favorite: false,
    verified: true,
    category: "education",
  },
  {
    id: 58,
    english: "book",
    darija: "ktab",
    type: "noun",
    arabic: "كتاب",
    favorite: false,
    verified: true,
    category: "education",
  },
  {
    id: 59,
    english: "notebook",
    darija: "dftar",
    type: "noun",
    arabic: "دفتر",
    favorite: false,
    verified: true,
    category: "education",
  },
  {
    id: 60,
    english: "elementary",
    darija: "btida2i",
    type: "noun",
    arabic: "ابتدائي",
    favorite: false,
    verified: false,
    category: "education",
  },
  {
    id: 61,
    english: "education",
    darija: "t3lim",
    type: "noun",
    arabic: "تعليم",
    favorite: false,
    verified: true,
    category: "education",
  },
  {
    id: 62,
    english: "school",
    darija: "mdrasa",
    type: "noun",
    arabic: "مدرسة",
    favorite: false,
    verified: false,
    category: "education",
  },
  {
    id: 63,
    english: "class",
    darija: "9ism",
    type: "noun",
    arabic: "قسم",
    favorite: true,
    verified: true,
    category: "education",
  },
  {
    id: 64,
    english: "faculty",
    darija: "lafak",
    type: "noun",
    arabic: "لافاك",
    favorite: false,
    verified: true,
    category: "education",
  },
  {
    id: 65,
    english: "middle school",
    darija: "i3dadi",
    type: "noun",
    arabic: "إعدادي",
    favorite: false,
    verified: true,
    category: "education",
  },
  {
    id: 66,
    english: "high school",
    darija: "tanawi",
    type: "noun",
    arabic: "تانوي",
    favorite: false,
    verified: true,
    category: "education",
  },
  {
    id: 67,
    english: "university",
    darija: "jami3a",
    type: "noun",
    arabic: "جامعة",
    favorite: false,
    verified: true,
    category: "education",
  },
  {
    id: 68,
    english: "diploma",
    darija: "diplom",
    type: "noun",
    arabic: "دپلوم",
    favorite: false,
    verified: false,
    category: "education",
  },
  {
    id: 69,
    english: "administration",
    darija: "idara",
    type: "noun",
    arabic: "إدارة",
    favorite: false,
    verified: true,
    category: "education",
  },
  {
    id: 70,
    english: "bench",
    darija: "Tawila",
    type: "noun",
    arabic: "طاولة",
    favorite: false,
    verified: true,
    category: "education",
  },
  {
    id: 71,
    english: "philosophy",
    darija: "flsafa",
    type: "noun",
    arabic: "فلسفة",
    favorite: false,
    verified: false,
    category: "education",
  },
  {
    id: 72,
    english: "subjects",
    darija: "mawad",
    type: "noun",
    arabic: "مواد",
    favorite: false,
    verified: false,
    category: "education",
  },
  {
    id: 73,
    english: "science",
    darija: "3ilm",
    type: "noun",
    arabic: "علم",
    favorite: false,
    verified: false,
    category: "education",
  },
  {
    id: 74,
    english: "language",
    darija: "logha",
    type: "noun",
    arabic: "لغة",
    favorite: false,
    verified: true,
    category: "education",
  },
  {
    id: 75,
    english: "literature",
    darija: "adab",
    type: "noun",
    arabic: "أداب",
    favorite: false,
    verified: false,
    category: "education",
  },
  {
    id: 76,
    english: "sciences",
    darija: "3oloum",
    type: "noun",
    arabic: "علوم",
    favorite: false,
    verified: true,
    category: "education",
  },
  {
    id: 77,
    english: "writing",
    darija: "ktba",
    type: "noun",
    arabic: "كتبة",
    favorite: false,
    verified: false,
    category: "education",
  },
  {
    id: 78,
    english: "algebra",
    darija: "jabr",
    type: "noun",
    arabic: "جبر",
    favorite: false,
    verified: true,
    category: "education",
  },
  {
    id: 79,
    english: "geometry",
    darija: "8ndasa",
    type: "noun",
    arabic: "هندسة",
    favorite: false,
    verified: true,
    category: "education",
  },
  {
    id: 80,
    english: "computing",
    darija: "l7sab",
    type: "noun",
    arabic: "لحساب",
    favorite: false,
    verified: false,
    category: "education",
  },
  {
    id: 81,
    english: "chemistry",
    darija: "chimi",
    type: "noun",
    arabic: "شيمي",
    favorite: false,
    verified: true,
    category: "education",
  },
  {
    id: 82,
    english: "pen",
    darija: "stilo",
    type: "noun",
    arabic: "ستيلو",
    favorite: false,
    verified: false,
    category: "education",
  },
  {
    id: 83,
    english: "ruler",
    darija: "misTara",
    type: "noun",
    arabic: "مسطرة",
    favorite: false,
    verified: false,
    category: "education",
  },
  {
    id: 84,
    english: "bag",
    darija: "chkara",
    type: "noun",
    arabic: "شكارة",
    favorite: false,
    verified: false,
    category: "education",
  },
  {
    id: 85,
    english: "pencil",
    darija: "9alam",
    type: "noun",
    arabic: "قلم",
    favorite: true,
    verified: false,
    category: "education",
  },
  {
    id: 86,
    english: "anger",
    darija: "ghaDab",
    type: "noun",
    arabic: "غضب",
    favorite: false,
    verified: true,
    category: "emotions",
  },
  {
    id: 87,
    english: "amusement",
    darija: "nachaT",
    type: "noun",
    arabic: "نشاط",
    favorite: false,
    verified: true,
    category: "emotions",
  },
  {
    id: 88,
    english: "acceptance",
    darija: "9oboul",
    type: "noun",
    arabic: "قبول",
    favorite: false,
    verified: true,
    category: "emotions",
  },
  {
    id: 89,
    english: "courage",
    darija: "chaja3a",
    type: "noun",
    arabic: "شجاعة",
    favorite: false,
    verified: false,
    category: "emotions",
  },
  {
    id: 90,
    english: "confidence",
    darija: "ti9a",
    type: "noun",
    arabic: "تقة",
    favorite: false,
    verified: false,
    category: "emotions",
  },
  {
    id: 91,
    english: "boredom",
    darija: "malal",
    type: "noun",
    arabic: "ملل",
    favorite: false,
    verified: false,
    category: "emotions",
  },
  {
    id: 92,
    english: "apathy",
    darija: "lamobalat",
    type: "noun",
    arabic: "لامبالاة",
    favorite: false,
    verified: true,
    category: "emotions",
  },
  {
    id: 93,
    english: "curiosity",
    darija: "fDoul",
    type: "noun",
    arabic: "فضول",
    favorite: false,
    verified: true,
    category: "emotions",
  },
  {
    id: 94,
    english: "depression",
    darija: "ka2aaba",
    type: "noun",
    arabic: "كآبة",
    favorite: false,
    verified: true,
    category: "emotions",
  },
  {
    id: 95,
    english: "desire",
    darija: "rghba",
    type: "noun",
    arabic: "رغبة",
    favorite: false,
    verified: true,
    category: "emotions",
  },
  {
    id: 96,
    english: "disgusting",
    darija: "tay3yef",
    type: "noun",
    arabic: "تايعيف",
    favorite: false,
    verified: true,
    category: "emotions",
  },
  {
    id: 97,
    english: "doubt",
    darija: "chek",
    type: "noun",
    arabic: "شك",
    favorite: false,
    verified: true,
    category: "emotions",
  },
  {
    id: 98,
    english: "ecstasy",
    darija: "nchwa",
    type: "noun",
    arabic: "نشوة",
    favorite: false,
    verified: true,
    category: "emotions",
  },
  {
    id: 99,
    english: "embarrassment",
    darija: "i7raj",
    type: "noun",
    arabic: "إحراج",
    favorite: false,
    verified: false,
    category: "emotions",
  },
  {
    id: 100,
    english: "faith",
    darija: "2ymane",
    type: "noun",
    arabic: "إيمان",
    favorite: false,
    verified: true,
    category: "emotions",
  },
  {
    id: 101,
    english: "fear",
    darija: "khouf",
    type: "noun",
    arabic: "خوف",
    favorite: false,
    verified: true,
    category: "emotions",
  },
  {
    id: 102,
    english: "frustration",
    darija: "i7baaT",
    type: "noun",
    arabic: "إحباط",
    favorite: false,
    verified: false,
    category: "emotions",
  },
  {
    id: 103,
    english: "empathy",
    darija: "ta3aTof",
    type: "noun",
    arabic: "تعاطف",
    favorite: false,
    verified: false,
    category: "emotions",
  },
  {
    id: 104,
    english: "gratitude",
    darija: "chokr",
    type: "noun",
    arabic: "شكر",
    favorite: false,
    verified: false,
    category: "emotions",
  },
  {
    id: 105,
    english: "greed",
    darija: "Tm3",
    type: "noun",
    arabic: "طمع",
    favorite: false,
    verified: false,
    category: "emotions",
  },
  {
    id: 106,
    english: "guilt",
    darija: "dnb",
    type: "noun",
    arabic: "دنب",
    favorite: false,
    verified: false,
    category: "emotions",
  },
  {
    id: 107,
    english: "family",
    darija: "3a2ila",
    type: "noun",
    arabic: "عائلة",
    favorite: true,
    verified: true,
    category: "family",
  },
  {
    id: 108,
    english: "my daughter",
    darija: "bnti",
    type: "noun",
    arabic: "بنتي",
    favorite: false,
    verified: false,
    category: "family",
  },
  {
    id: 109,
    english: "my son",
    darija: "wldi",
    type: "noun",
    arabic: "ولدي",
    favorite: false,
    verified: true,
    category: "family",
  },
  {
    id: 110,
    english: "father",
    darija: "lwalid",
    type: "noun",
    arabic: "لواليد",
    favorite: false,
    verified: false,
    category: "family",
  },
  {
    id: 111,
    english: "mother",
    darija: "lwalida",
    type: "noun",
    arabic: "لواليدة",
    favorite: true,
    verified: true,
    category: "family",
  },
  {
    id: 112,
    english: "dad",
    darija: "baba",
    type: "noun",
    arabic: "بابا",
    favorite: false,
    verified: true,
    category: "family",
  },
  {
    id: 113,
    english: "mom",
    darija: "mama",
    type: "noun",
    arabic: "ماما",
    favorite: false,
    verified: false,
    category: "family",
  },
  {
    id: 114,
    english: "my brother",
    darija: "khouya",
    type: "noun",
    arabic: "خويا",
    favorite: false,
    verified: true,
    category: "family",
  },
  {
    id: 115,
    english: "my sister",
    darija: "khti",
    type: "noun",
    arabic: "ختي",
    favorite: false,
    verified: true,
    category: "family",
  },
  {
    id: 116,
    english: "my uncle",
    darija: "3mi",
    type: "noun",
    arabic: "عمي",
    favorite: false,
    verified: true,
    category: "family",
  },
  {
    id: 117,
    english: "my aunt",
    darija: "3mti",
    type: "noun",
    arabic: "عمتي",
    favorite: false,
    verified: false,
    category: "family",
  },
  {
    id: 118,
    english: "my uncle",
    darija: "khali",
    type: "noun",
    arabic: "خالي",
    favorite: false,
    verified: true,
    category: "family",
  },
  {
    id: 119,
    english: "my aunt",
    darija: "khalti",
    type: "noun",
    arabic: "خالتي",
    favorite: false,
    verified: true,
    category: "family",
  },
  {
    id: 120,
    english: "vegetables",
    darija: "khDra",
    type: "noun",
    arabic: "خضرة",
    favorite: false,
    verified: true,
    category: "food",
  },
  {
    id: 121,
    english: "onion",
    darija: "bsla",
    type: "noun",
    arabic: "بصلة",
    favorite: false,
    verified: false,
    category: "food",
  },
  {
    id: 122,
    english: "tomato",
    darija: "maticha",
    type: "noun",
    arabic: "مطيشة",
    favorite: false,
    verified: true,
    category: "food",
  },
  {
    id: 123,
    english: "pea",
    darija: "jelbana",
    type: "noun",
    arabic: "جلبانة",
    favorite: false,
    verified: true,
    category: "food",
  },
  {
    id: 124,
    english: "eggplant",
    darija: "dnjal",
    type: "noun",
    arabic: "دنجال",
    favorite: false,
    verified: true,
    category: "food",
  },
  {
    id: 125,
    english: "pumpkin",
    darija: "gar3a",
    type: "noun",
    arabic: "ڭرعة",
    favorite: false,
    verified: true,
    category: "food",
  },
  {
    id: 126,
    english: "cabbage",
    darija: "mkowwr",
    type: "noun",
    arabic: "مكوّر",
    favorite: false,
    verified: false,
    category: "food",
  },
  {
    id: 127,
    english: "potato",
    darija: "btata",
    type: "noun",
    arabic: "بطاطا",
    favorite: false,
    verified: true,
    category: "food",
  },
  {
    id: 128,
    english: "cucumber",
    darija: "khyar",
    type: "noun",
    arabic: "خيار",
    favorite: false,
    verified: true,
    category: "food",
  },
  {
    id: 129,
    english: "carrot",
    darija: "khizo",
    type: "noun",
    arabic: "خيزو",
    favorite: false,
    verified: false,
    category: "food",
  },
  {
    id: 130,
    english: "garlic",
    darija: "touma",
    type: "noun",
    arabic: "تومة",
    favorite: false,
    verified: true,
    category: "food",
  },
  {
    id: 131,
    english: "cauliflower",
    darija: "chiflour",
    type: "noun",
    arabic: "شيفلور",
    favorite: false,
    verified: true,
    category: "food",
  },
  {
    id: 132,
    english: "artichokes",
    darija: "9o9",
    type: "noun",
    arabic: "قوق",
    favorite: false,
    verified: true,
    category: "food",
  },
  {
    id: 133,
    english: "cardoon",
    darija: "khrchouf",
    type: "noun",
    arabic: "خرشوف",
    favorite: false,
    verified: true,
    category: "food",
  },
  {
    id: 134,
    english: "pepper",
    darija: "flfla",
    type: "noun",
    arabic: "فلفلة",
    favorite: false,
    verified: false,
    category: "food",
  },
  {
    id: 135,
    english: "radishes",
    darija: "fjl",
    type: "noun",
    arabic: "فجل",
    favorite: false,
    verified: false,
    category: "food",
  },
  {
    id: 136,
    english: "beans",
    darija: "loubia",
    type: "noun",
    arabic: "لوبيا",
    favorite: false,
    verified: true,
    category: "food",
  },
  {
    id: 137,
    english: "fennel",
    darija: "bsbas",
    type: "noun",
    arabic: "بسباس",
    favorite: false,
    verified: true,
    category: "food",
  },
  {
    id: 138,
    english: "lettuce",
    darija: "khoss",
    type: "noun",
    arabic: "خص",
    favorite: false,
    verified: true,
    category: "food",
  },
  {
    id: 139,
    english: "turnip",
    darija: "lft",
    type: "noun",
    arabic: "لفت",
    favorite: false,
    verified: true,
    category: "food",
  },
  {
    id: 140,
    english: "maize",
    darija: "kbal",
    type: "noun",
    arabic: "كبال",
    favorite: false,
    verified: false,
    category: "food",
  },
  {
    id: 141,
    english: "coriander",
    darija: "9zbour",
    type: "noun",
    arabic: "قزبور",
    favorite: false,
    verified: false,
    category: "food",
  },
  {
    id: 142,
    english: "parsley",
    darija: "m3dnous",
    type: "noun",
    arabic: "معدنوس",
    favorite: false,
    verified: true,
    category: "food",
  },
  {
    id: 143,
    english: "olives",
    darija: "zitoun",
    type: "noun",
    arabic: "زيتون",
    favorite: false,
    verified: false,
    category: "food",
  },
  {
    id: 144,
    english: "beet",
    darija: "barba",
    type: "noun",
    arabic: "باربا",
    favorite: false,
    verified: true,
    category: "food",
  },
  {
    id: 145,
    english: "celery",
    darija: "krafS",
    type: "noun",
    arabic: "كرافص",
    favorite: false,
    verified: false,
    category: "food",
  },
  {
    id: 146,
    english: "courgette",
    darija: "kourjiT",
    type: "noun",
    arabic: "كورجيط",
    favorite: false,
    verified: true,
    category: "food",
  },
  {
    id: 147,
    english: "vegetables",
    darija: "khDra",
    type: "noun",
    arabic: "خضرة",
    favorite: false,
    verified: true,
    category: "food",
  },
  {
    id: 148,
    english: "fruits",
    darija: "dissir",
    type: "noun",
    arabic: "ديسير",
    favorite: false,
    verified: true,
    category: "food",
  },
  {
    id: 149,
    english: "apple",
    darija: "tfa7",
    type: "noun",
    arabic: "تفاح",
    favorite: false,
    verified: true,
    category: "food",
  },
  {
    id: 150,
    english: "pear",
    darija: "bou3ouid",
    type: "noun",
    arabic: "بوعويد",
    favorite: false,
    verified: false,
    category: "food",
  },
  {
    id: 151,
    english: "strawberry",
    darija: "friz",
    type: "noun",
    arabic: "فريز",
    favorite: false,
    verified: true,
    category: "food",
  },
  {
    id: 152,
    english: "avocado",
    darija: "avoka",
    type: "noun",
    arabic: "أڤوكا",
    favorite: false,
    verified: true,
    category: "food",
  },
  {
    id: 153,
    english: "grape",
    darija: "3nb",
    type: "noun",
    arabic: "عنب",
    favorite: false,
    verified: false,
    category: "food",
  },
  {
    id: 154,
    english: "fig",
    darija: "krmous",
    type: "noun",
    arabic: "كرموس",
    favorite: false,
    verified: false,
    category: "food",
  },
  {
    id: 155,
    english: "orange",
    darija: "limoun",
    type: "noun",
    arabic: "ليمون",
    favorite: false,
    verified: true,
    category: "food",
  },
  {
    id: 156,
    english: "lemon",
    darija: "7amd",
    type: "noun",
    arabic: "حامض",
    favorite: false,
    verified: true,
    category: "food",
  },
  {
    id: 157,
    english: "pomegranate",
    darija: "rman",
    type: "noun",
    arabic: "رمان",
    favorite: false,
    verified: true,
    category: "food",
  },
  {
    id: 158,
    english: "watermelon",
    darija: "dla7",
    type: "noun",
    arabic: "دلاح",
    favorite: false,
    verified: true,
    category: "food",
  },
  {
    id: 159,
    english: "peach",
    darija: "khoukh",
    type: "noun",
    arabic: "خوخ",
    favorite: false,
    verified: false,
    category: "food",
  },
  {
    id: 160,
    english: "kiwi",
    darija: "kiwi",
    type: "noun",
    arabic: "كيوي",
    favorite: false,
    verified: false,
    category: "food",
  },
  {
    id: 161,
    english: "influenza",
    darija: "rrwa7",
    type: "noun",
    arabic: "الرواح",
    favorite: false,
    verified: false,
    category: "health",
  },
  {
    id: 162,
    english: "diabetes",
    darija: "skkar",
    type: "noun",
    arabic: "سكّار",
    favorite: false,
    verified: true,
    category: "health",
  },
  {
    id: 163,
    english: "ache",
    darija: "Sda3",
    type: "noun",
    arabic: "صداع",
    favorite: false,
    verified: true,
    category: "health",
  },
  {
    id: 164,
    english: "allergy",
    darija: "7asasia",
    type: "noun",
    arabic: "حساسية",
    favorite: false,
    verified: false,
    category: "health",
  },
  {
    id: 165,
    english: "asthma",
    darija: "DDi9a",
    type: "noun",
    arabic: "الضيقا",
    favorite: false,
    verified: true,
    category: "health",
  },
  {
    id: 166,
    english: "breathing",
    darija: "tanffous",
    type: "noun",
    arabic: "تنفّس",
    favorite: false,
    verified: false,
    category: "health",
  },
  {
    id: 167,
    english: "healthy",
    darija: "S7i7",
    type: "noun",
    arabic: "صحيح",
    favorite: false,
    verified: true,
    category: "health",
  },
  {
    id: 168,
    english: "ill",
    darija: "mriD",
    type: "noun",
    arabic: "مريض",
    favorite: false,
    verified: false,
    category: "health",
  },
  {
    id: 169,
    english: "medicine",
    darija: "Tibb",
    type: "noun",
    arabic: "طبّ",
    favorite: false,
    verified: false,
    category: "health",
  },
  {
    id: 170,
    english: "hospital",
    darija: "sbiTar",
    type: "noun",
    arabic: "سبيطار",
    favorite: false,
    verified: false,
    category: "health",
  },
  {
    id: 171,
    english: "ambulance",
    darija: "labilanS",
    type: "noun",
    arabic: "لابيلانص",
    favorite: false,
    verified: true,
    category: "health",
  },
  {
    id: 172,
    english: "disease",
    darija: "maraD",
    type: "noun",
    arabic: "مرض",
    favorite: false,
    verified: true,
    category: "health",
  },
  {
    id: 173,
    english: "human",
    darija: "bnadm",
    type: "noun",
    arabic: "بنادم",
    favorite: false,
    verified: false,
    category: "body",
  },
  {
    id: 174,
    english: "foot",
    darija: "rjl",
    type: "noun",
    arabic: "رجل",
    favorite: false,
    verified: true,
    category: "body",
  },
  {
    id: 175,
    english: "hand",
    darija: "yedd",
    type: "noun",
    arabic: "يدّ",
    favorite: false,
    verified: false,
    category: "body",
  },
  {
    id: 176,
    english: "eye",
    darija: "3in",
    type: "noun",
    arabic: "عين",
    favorite: false,
    verified: true,
    category: "body",
  },
  {
    id: 177,
    english: "nose",
    darija: "nif",
    type: "noun",
    arabic: "نيف",
    favorite: false,
    verified: false,
    category: "body",
  },
  {
    id: 178,
    english: "nose",
    darija: "mnakher",
    type: "noun",
    arabic: "مناخر",
    favorite: false,
    verified: true,
    category: "body",
  },
  {
    id: 179,
    english: "mouth",
    darija: "fom",
    type: "noun",
    arabic: "فم",
    favorite: false,
    verified: false,
    category: "body",
  },
  {
    id: 180,
    english: "brain",
    darija: "dmagh",
    type: "noun",
    arabic: "دماغ",
    favorite: false,
    verified: true,
    category: "body",
  },
  {
    id: 181,
    english: "liver",
    darija: "kbda",
    type: "noun",
    arabic: "كبدة",
    favorite: false,
    verified: false,
    category: "body",
  },
  {
    id: 182,
    english: "lung",
    darija: "riyya",
    type: "noun",
    arabic: "رية",
    favorite: false,
    verified: false,
    category: "body",
  },
  {
    id: 183,
    english: "kidney",
    darija: "klwa",
    type: "noun",
    arabic: "كلوة",
    favorite: false,
    verified: true,
    category: "body",
  },
  {
    id: 184,
    english: "stomach",
    darija: "m3da",
    type: "noun",
    arabic: "معدة",
    favorite: false,
    verified: false,
    category: "body",
  },
  {
    id: 185,
    english: "bone",
    darija: "3Dm",
    type: "noun",
    arabic: "عضم",
    favorite: false,
    verified: false,
    category: "body",
  },
  {
    id: 186,
    english: "intestine",
    darija: "mSarn",
    type: "noun",
    arabic: "مصارن",
    favorite: false,
    verified: true,
    category: "body",
  },
  {
    id: 187,
    english: "number",
    darija: "ra9m",
    type: "noun",
    arabic: "رقم",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 189,
    english: "zero",
    darija: "Sifr",
    type: "noun",
    arabic: "صفر",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 191,
    english: "one",
    darija: "wahd",
    type: "noun",
    arabic: "واحد",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 192,
    english: "two",
    darija: "jouj",
    type: "noun",
    arabic: "جوج",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 193,
    english: "three",
    darija: "tlata",
    type: "noun",
    arabic: "تلاتة",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 194,
    english: "four",
    darija: "rb3a",
    type: "noun",
    arabic: "ربعة",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 195,
    english: "five",
    darija: "khmsa",
    type: "noun",
    arabic: "خمسة",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 196,
    english: "six",
    darija: "stta",
    type: "noun",
    arabic: "ستّة",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 197,
    english: "seven",
    darija: "sb3a",
    type: "noun",
    arabic: "سبعة",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 198,
    english: "eight",
    darija: "tmnia",
    type: "noun",
    arabic: "تمنية",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 199,
    english: "nine",
    darija: "ts3oud",
    type: "noun",
    arabic: "تسعود",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 200,
    english: "nine",
    darija: "ts3a",
    type: "noun",
    arabic: "تسعة",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 201,
    english: "ten",
    darija: "3chra",
    type: "noun",
    arabic: "عشرة",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 202,
    english: "eleven",
    darija: "7Dach",
    type: "noun",
    arabic: "حضاش",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 203,
    english: "twelve",
    darija: "Tnach",
    type: "noun",
    arabic: "طناش",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 204,
    english: "thirteen",
    darija: "TlTTach",
    type: "noun",
    arabic: "طلطّاش",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 205,
    english: "fourteen",
    darija: "rb3Tach",
    type: "noun",
    arabic: "ربعطاش",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 206,
    english: "fifteen",
    darija: "khmsTach",
    type: "noun",
    arabic: "خمسطاش",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 207,
    english: "sixteen",
    darija: "sTTach",
    type: "noun",
    arabic: "سطّاش",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 208,
    english: "seventeen",
    darija: "sb3Tach",
    type: "noun",
    arabic: "سبعطاش",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 209,
    english: "eighteen",
    darija: "tmnTach",
    type: "noun",
    arabic: "تمنطاش",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 210,
    english: "nineteen",
    darija: "ts3Tach",
    type: "noun",
    arabic: "تسعطاش",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 211,
    english: "twenty",
    darija: "3chrin",
    type: "noun",
    arabic: "عشرين",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 212,
    english: "twenty one",
    darija: "wahd o 3chrin",
    type: "noun",
    arabic: "واحد و عشرين",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 213,
    english: "twenty two",
    darija: "tnayn o 3chrin",
    type: "noun",
    arabic: "تناين و عشرين",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 214,
    english: "twenty three",
    darija: "tlata o 3chrin",
    type: "noun",
    arabic: "تلاتة و عشرين",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 215,
    english: "twenty four",
    darija: "rb3a o 3chrin",
    type: "noun",
    arabic: "ربعة و عشرين",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 216,
    english: "twenty five",
    darija: "khmsa o 3chrin",
    type: "noun",
    arabic: "خمسة و عشرين",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 217,
    english: "twenty six",
    darija: "stta o 3chrin",
    type: "noun",
    arabic: "ستّة و عشرين",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 218,
    english: "twenty seven",
    darija: "sb3a o 3chrin",
    type: "noun",
    arabic: "سبعة و عشرين",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 219,
    english: "twenty eight",
    darija: "tmnya o 3chrin",
    type: "noun",
    arabic: "تمنية و عشرين",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 220,
    english: "twenty nine",
    darija: "ts3oud o 3chrin",
    type: "noun",
    arabic: "تسعود و عشرين",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 221,
    english: "thirty",
    darija: "tlatin",
    type: "noun",
    arabic: "تلاتين",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 222,
    english: "forty",
    darija: "rb3in",
    type: "noun",
    arabic: "ربعين",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 223,
    english: "fifty",
    darija: "khmsin",
    type: "noun",
    arabic: "خمسين",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 224,
    english: "sixty",
    darija: "stin",
    type: "noun",
    arabic: "ستين",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 225,
    english: "seventy",
    darija: "sb3in",
    type: "noun",
    arabic: "سبعين",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 226,
    english: "eighty",
    darija: "tmanin",
    type: "noun",
    arabic: "تمانين",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 227,
    english: "ninety",
    darija: "ts3in",
    type: "noun",
    arabic: "تسعين",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 228,
    english: "ninety one",
    darija: "wahd o ts3in",
    type: "noun",
    arabic: "واحد و تسعين",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 229,
    english: "ninety two",
    darija: "tnayn o ts3in",
    type: "noun",
    arabic: "تناين و تسعين",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 230,
    english: "ninety three",
    darija: "tlata o ts3in",
    type: "noun",
    arabic: "تلاتة و تسعين",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 231,
    english: "ninety four",
    darija: "rb3a o ts3in",
    type: "noun",
    arabic: "ربعة و تسعين",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 232,
    english: "ninety five",
    darija: "khmsa o ts3in",
    type: "noun",
    arabic: "خمسة و تسعين",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 233,
    english: "ninety six",
    darija: "stta o ts3in",
    type: "noun",
    arabic: "ستّة و تسعين",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 234,
    english: "ninety seven",
    darija: "sb3a o ts3in",
    type: "noun",
    arabic: "سبعة و تسعين",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 235,
    english: "ninety eight",
    darija: "tmnya o ts3in",
    type: "noun",
    arabic: "تمنية و تسعين",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 236,
    english: "ninety nine",
    darija: "ts3oud o ts3in",
    type: "noun",
    arabic: "تسعود و تسعين",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 237,
    english: "hundred",
    darija: "myya",
    type: "noun",
    arabic: "ميّة",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 238,
    english: "thousand",
    darija: "alf",
    type: "noun",
    arabic: "ألف",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 239,
    english: "thousands",
    darija: "alaf",
    type: "noun",
    arabic: "آلاف",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 240,
    english: "million",
    darija: "mlyon",
    type: "noun",
    arabic: "مليون",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 241,
    english: "billion",
    darija: "mlyar",
    type: "noun",
    arabic: "مليار",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 242,
    english: "and",
    darija: "w",
    type: "noun",
    arabic: "و",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 243,
    english: "first",
    darija: "lwwl",
    type: "noun",
    arabic: "لوّل",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 244,
    english: "second",
    darija: "ttani",
    type: "noun",
    arabic: "التاني",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 245,
    english: "third",
    darija: "ttalt",
    type: "noun",
    arabic: "التالت",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 246,
    english: "fourth",
    darija: "rrab3",
    type: "noun",
    arabic: "الرابع",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 247,
    english: "fifth",
    darija: "lkhams",
    type: "noun",
    arabic: "لخامس",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 248,
    english: "sixth",
    darija: "ssads",
    type: "noun",
    arabic: "السادس",
    favorite: true,
    verified: false,
    category: "numbers",
  },
  {
    id: 249,
    english: "seventh",
    darija: "ssab3",
    type: "noun",
    arabic: "السابع",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 250,
    english: "eighth",
    darija: "ttamn",
    type: "noun",
    arabic: "التامن",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 251,
    english: "ninth",
    darija: "ttas3",
    type: "noun",
    arabic: "التاسع",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 252,
    english: "tenth",
    darija: "l3achr",
    type: "noun",
    arabic: "لعاشر",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 253,
    english: "last",
    darija: "llkher",
    type: "noun",
    arabic: "اللخر",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 254,
    english: "one-third",
    darija: "ttolot",
    type: "noun",
    arabic: "التلت",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 255,
    english: "one-fourth",
    darija: "rrobo3",
    type: "noun",
    arabic: "الربع",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 256,
    english: "one-fifth",
    darija: "lkhomos",
    type: "noun",
    arabic: "لخمس",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 257,
    english: "one-sixth",
    darija: "ssodos",
    type: "noun",
    arabic: "السدس",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 258,
    english: "one-seventh",
    darija: "ssobo3",
    type: "noun",
    arabic: "السبع",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 259,
    english: "one-eighth",
    darija: "ttomon",
    type: "noun",
    arabic: "التمن",
    favorite: false,
    verified: true,
    category: "numbers",
  },
  {
    id: 260,
    english: "one-tenth",
    darija: "l3ochor",
    type: "noun",
    arabic: "لعشر",
    favorite: false,
    verified: false,
    category: "numbers",
  },
  {
    id: 261,
    english: "planet",
    darija: "kawkab",
    type: "noun",
    arabic: "كوكب",
    favorite: false,
    verified: false,
    category: "places",
  },
  {
    id: 262,
    english: "continent",
    darija: "9aarra",
    type: "noun",
    arabic: "قارّة",
    favorite: false,
    verified: false,
    category: "places",
  },
  {
    id: 263,
    english: "africa",
    darija: "ifri9ia",
    type: "noun",
    arabic: "إفريقيا",
    favorite: false,
    verified: true,
    category: "places",
  },
  {
    id: 264,
    english: "europe",
    darija: "europa",
    type: "noun",
    arabic: "أوربا",
    favorite: false,
    verified: false,
    category: "places",
  },
  {
    id: 265,
    english: "country",
    darija: "blad",
    type: "noun",
    arabic: "بلاد",
    favorite: false,
    verified: true,
    category: "places",
  },
  {
    id: 266,
    english: "country",
    darija: "dawla",
    type: "noun",
    arabic: "دولة",
    favorite: false,
    verified: false,
    category: "places",
  },
  {
    id: 267,
    english: "morocco",
    darija: "mghrib",
    type: "noun",
    arabic: "المغرب",
    favorite: false,
    verified: true,
    category: "places",
  },
  {
    id: 268,
    english: "rose",
    darija: "wrda",
    type: "noun",
    arabic: "وردة",
    favorite: false,
    verified: false,
    category: "plants",
  },
  {
    id: 269,
    english: "plant",
    darija: "nbta",
    type: "noun",
    arabic: "نبتة",
    favorite: false,
    verified: true,
    category: "plants",
  },
  {
    id: 270,
    english: "thorn",
    darija: "chouk",
    type: "noun",
    arabic: "شوك",
    favorite: false,
    verified: false,
    category: "plants",
  },
  {
    id: 271,
    english: "palm tree",
    darija: "nkhla",
    type: "noun",
    arabic: "نخلة",
    favorite: false,
    verified: false,
    category: "plants",
  },
  {
    id: 272,
    english: "tree",
    darija: "chjra",
    type: "noun",
    arabic: "شجرة",
    favorite: false,
    verified: true,
    category: "plants",
  },
  {
    id: 273,
    english: "trees",
    darija: "chjr",
    type: "noun",
    arabic: "شجر",
    favorite: false,
    verified: true,
    category: "plants",
  },
  {
    id: 274,
    english: "cactus",
    darija: "Sbbar",
    type: "noun",
    arabic: "صبّار",
    favorite: false,
    verified: true,
    category: "plants",
  },
  {
    id: 275,
    english: "willow",
    darija: "SafSaf",
    type: "noun",
    arabic: "صفصاف",
    favorite: false,
    verified: true,
    category: "plants",
  },
  {
    id: 276,
    english: "pine",
    darija: "Sanawbar",
    type: "noun",
    arabic: "صنوبر",
    favorite: false,
    verified: false,
    category: "plants",
  },
  {
    id: 277,
    english: "branch",
    darija: "3rch",
    type: "noun",
    arabic: "عرش",
    favorite: false,
    verified: false,
    category: "plants",
  },
  {
    id: 278,
    english: "iris",
    darija: "sawsan",
    type: "noun",
    arabic: "سوسن",
    favorite: false,
    verified: false,
    category: "plants",
  },
  {
    id: 279,
    english: "barber",
    darija: "7jjam",
    type: "noun",
    arabic: "حجّام",
    favorite: false,
    verified: false,
    category: "professions",
  },
  {
    id: 280,
    english: "barber",
    darija: "7lla9",
    type: "noun",
    arabic: "حلّاق",
    favorite: false,
    verified: false,
    category: "professions",
  },
  {
    id: 281,
    english: "butcher",
    darija: "gzzar",
    type: "noun",
    arabic: "ڭزّار",
    favorite: false,
    verified: true,
    category: "professions",
  },
  {
    id: 282,
    english: "doctor",
    darija: "Tbib",
    type: "noun",
    arabic: "طبيب",
    favorite: false,
    verified: true,
    category: "professions",
  },
  {
    id: 283,
    english: "nurse",
    darija: "frmlia",
    type: "noun",
    arabic: "فرملية",
    favorite: false,
    verified: true,
    category: "professions",
  },
  {
    id: 284,
    english: "director",
    darija: "modir",
    type: "noun",
    arabic: "مدير",
    favorite: false,
    verified: false,
    category: "professions",
  },
  {
    id: 285,
    english: "artist",
    darija: "fnnan",
    type: "noun",
    arabic: "فنّان",
    favorite: false,
    verified: false,
    category: "professions",
  },
  {
    id: 286,
    english: "electrician",
    darija: "trisyan",
    type: "noun",
    arabic: "تريسيان",
    favorite: false,
    verified: true,
    category: "professions",
  },
  {
    id: 287,
    english: "engineer",
    darija: "mo8ndis",
    type: "noun",
    arabic: "مهندس",
    favorite: false,
    verified: true,
    category: "professions",
  },
  {
    id: 288,
    english: "peasant",
    darija: "flla7",
    type: "noun",
    arabic: "فلّاح",
    favorite: false,
    verified: true,
    category: "professions",
  },
  {
    id: 289,
    english: "journalist",
    darija: "Sa7afi",
    type: "noun",
    arabic: "صحفي",
    favorite: false,
    verified: false,
    category: "professions",
  },
  {
    id: 290,
    english: "judge",
    darija: "9aDi",
    type: "noun",
    arabic: "قاضي",
    favorite: false,
    verified: true,
    category: "professions",
  },
  {
    id: 291,
    english: "lawyer",
    darija: "mo7ami",
    type: "noun",
    arabic: "محامي",
    favorite: false,
    verified: true,
    category: "professions",
  },
  {
    id: 292,
    english: "mechanic",
    darija: "mikanisyan",
    type: "noun",
    arabic: "ميكانيسيان",
    favorite: false,
    verified: true,
    category: "professions",
  },
  {
    id: 293,
    english: "prosecutor",
    darija: "wakil",
    type: "noun",
    arabic: "وكيل",
    favorite: false,
    verified: false,
    category: "professions",
  },
  {
    id: 294,
    english: "cop",
    darija: "bolisi",
    type: "noun",
    arabic: "بوليسي",
    favorite: false,
    verified: false,
    category: "professions",
  },
  {
    id: 295,
    english: "gendarme",
    darija: "jadarmi",
    type: "noun",
    arabic: "جدارمي",
    favorite: false,
    verified: false,
    category: "professions",
  },
  {
    id: 296,
    english: "painter",
    darija: "rssam",
    type: "noun",
    arabic: "رسّام",
    favorite: false,
    verified: false,
    category: "professions",
  },
  {
    id: 297,
    english: "photographer",
    darija: "moSwwir",
    type: "noun",
    arabic: "مصوّر",
    favorite: false,
    verified: false,
    category: "professions",
  },
  {
    id: 298,
    english: "waiter",
    darija: "srbay",
    type: "noun",
    arabic: "سرباي",
    favorite: false,
    verified: true,
    category: "professions",
  },
  {
    id: 299,
    english: "waitress",
    darija: "srbaya",
    type: "noun",
    arabic: "سرباية",
    favorite: false,
    verified: false,
    category: "professions",
  },
  {
    id: 300,
    english: "tailor",
    darija: "khyyaT",
    type: "noun",
    arabic: "خيّاط",
    favorite: false,
    verified: false,
    category: "professions",
  },
  {
    id: 301,
    english: "ambassador",
    darija: "safir",
    type: "noun",
    arabic: "سفير",
    favorite: false,
    verified: true,
    category: "professions",
  },
  {
    id: 302,
    english: "advisor",
    darija: "mostachar",
    type: "noun",
    arabic: "مستشار",
    favorite: false,
    verified: true,
    category: "professions",
  },
  {
    id: 303,
    english: "pray",
    darija: "SSla",
    type: "noun",
    arabic: "الصلاة",
    favorite: false,
    verified: true,
    category: "religion",
  },
  {
    id: 304,
    english: "fasting",
    darija: "Syam",
    type: "noun",
    arabic: "صيام",
    favorite: false,
    verified: true,
    category: "religion",
  },
  {
    id: 305,
    english: "pilgrimage",
    darija: "lhej",
    type: "noun",
    arabic: "الحج",
    favorite: false,
    verified: true,
    category: "religion",
  },
  {
    id: 306,
    english: "charity",
    darija: "zakat",
    type: "noun",
    arabic: "زكاة",
    favorite: false,
    verified: false,
    category: "religion",
  },
  {
    id: 307,
    english: "mosque",
    darija: "jam3",
    type: "noun",
    arabic: "جامع",
    favorite: false,
    verified: false,
    category: "religion",
  },
  {
    id: 308,
    english: "jews",
    darija: "lihoud",
    type: "noun",
    arabic: "ليهود",
    favorite: false,
    verified: false,
    category: "religion",
  },
  {
    id: 309,
    english: "christians",
    darija: "nSara",
    type: "noun",
    arabic: "نصارا",
    favorite: false,
    verified: false,
    category: "religion",
  },
  {
    id: 310,
    english: "faith",
    darija: "imane",
    type: "noun",
    arabic: "إيمان",
    favorite: false,
    verified: false,
    category: "religion",
  },
  {
    id: 311,
    english: "unbelievers",
    darija: "koffar",
    type: "noun",
    arabic: "كفّار",
    favorite: false,
    verified: true,
    category: "religion",
  },
  {
    id: 312,
    english: "soul",
    darija: "rou7",
    type: "noun",
    arabic: "روح",
    favorite: false,
    verified: true,
    category: "religion",
  },
  {
    id: 313,
    english: "heaven",
    darija: "jenna",
    type: "noun",
    arabic: "جنّة",
    favorite: false,
    verified: false,
    category: "religion",
  },
  {
    id: 314,
    english: "hell",
    darija: "nnar",
    type: "noun",
    arabic: "النار",
    favorite: false,
    verified: true,
    category: "religion",
  },
  {
    id: 315,
    english: "hell",
    darija: "jahnam",
    type: "noun",
    arabic: "جهنم",
    favorite: false,
    verified: false,
    category: "religion",
  },
  {
    id: 316,
    english: "afterlife",
    darija: "lakhra",
    type: "noun",
    arabic: "لاخرة",
    favorite: false,
    verified: false,
    category: "religion",
  },
  {
    id: 317,
    english: "alcohol",
    darija: "chrab",
    type: "noun",
    arabic: "شراب",
    favorite: false,
    verified: true,
    category: "religion",
  },
  {
    id: 318,
    english: "angel",
    darija: "malak",
    type: "noun",
    arabic: "ملك",
    favorite: false,
    verified: true,
    category: "religion",
  },
  {
    id: 319,
    english: "religion",
    darija: "ddin",
    type: "noun",
    arabic: "الدين",
    favorite: false,
    verified: false,
    category: "religion",
  },
  {
    id: 320,
    english: "sports",
    darija: "riaDa",
    type: "noun",
    arabic: "رياضة",
    favorite: false,
    verified: true,
    category: "sports",
  },
  {
    id: 321,
    english: "soccer",
    darija: "kora",
    type: "noun",
    arabic: "كورة",
    favorite: false,
    verified: true,
    category: "sports",
  },
  {
    id: 322,
    english: "boxing",
    darija: "box",
    type: "noun",
    arabic: "بوكس",
    favorite: false,
    verified: false,
    category: "sports",
  },
  {
    id: 323,
    english: "jogging",
    darija: "jjra",
    type: "noun",
    arabic: "الجرا",
    favorite: false,
    verified: false,
    category: "sports",
  },
  {
    id: 324,
    english: "stadium",
    darija: "tirane",
    type: "noun",
    arabic: "تيران",
    favorite: false,
    verified: true,
    category: "sports",
  },
  {
    id: 325,
    english: "shirt",
    darija: "touni",
    type: "noun",
    arabic: "توني",
    favorite: false,
    verified: true,
    category: "sports",
  },
  {
    id: 326,
    english: "gloves",
    darija: "ligat",
    type: "noun",
    arabic: "ليڭات",
    favorite: false,
    verified: false,
    category: "sports",
  },
  {
    id: 327,
    english: "gym",
    darija: "lasal",
    type: "noun",
    arabic: "لاصال",
    favorite: false,
    verified: false,
    category: "sports",
  },
  {
    id: 328,
    english: "bodybuilding",
    darija: "l7did",
    type: "noun",
    arabic: "لحديد",
    favorite: false,
    verified: false,
    category: "sports",
  },
  {
    id: 329,
    english: "second",
    darija: "tania",
    type: "noun",
    arabic: "تانية",
    favorite: false,
    verified: true,
    category: "time",
  },
  {
    id: 330,
    english: "minute",
    darija: "d9i9a",
    type: "noun",
    arabic: "دقيقة",
    favorite: false,
    verified: false,
    category: "time",
  },
  {
    id: 331,
    english: "hour",
    darija: "sa3a",
    type: "noun",
    arabic: "ساعة",
    favorite: false,
    verified: true,
    category: "time",
  },
  {
    id: 332,
    english: "day",
    darija: "yawm",
    type: "noun",
    arabic: "يوم",
    favorite: false,
    verified: false,
    category: "time",
  },
  {
    id: 333,
    english: "yesterday",
    darija: "lbar7",
    type: "noun",
    arabic: "لبارح",
    favorite: false,
    verified: false,
    category: "time",
  },
  {
    id: 334,
    english: "now",
    darija: "daba",
    type: "noun",
    arabic: "دابا",
    favorite: false,
    verified: true,
    category: "time",
  },
  {
    id: 335,
    english: "today",
    darija: "lyom",
    type: "noun",
    arabic: "ليوم",
    favorite: false,
    verified: true,
    category: "time",
  },
  {
    id: 336,
    english: "tomorrow",
    darija: "ghdda",
    type: "noun",
    arabic: "غدّا",
    favorite: false,
    verified: true,
    category: "time",
  },
  {
    id: 337,
    english: "hi",
    darija: "salam",
    type: "noun",
    arabic: "سلام",
    favorite: false,
    verified: true,
    category: null,
  },
  {
    id: 338,
    english: "always",
    darija: "dima",
    type: "adverb",
    arabic: "ديما",
    favorite: false,
    verified: false,
    category: null,
  },
  {
    id: 339,
    english: "below",
    darija: "t7t",
    type: "preposition",
    arabic: "تحت",
    favorite: false,
    verified: true,
    category: null,
  },
  {
    id: 340,
    english: "slowly",
    darija: "bchwiya",
    type: "adverb",
    arabic: "بشوية",
    favorite: false,
    verified: true,
    category: null,
  },
  {
    id: 341,
    english: "look",
    darija: "chof",
    type: "verb",
    arabic: "شوف",
    favorite: false,
    verified: true,
    category: null,
  },
];

export const dummyCategories: string[] = [
  "family",
  "clothes",
  "food",
  "education",
  "colors",
  "numbers",
  "sports",
  "health",
  "animals",
  "plants",
  "emotions",
  "places",
  "professions",
  "body",
  "time",
  "religion",
  "nature",
  "objects",
];

export const dummyCommunityPosts: ICommunityPost[] = [
  {
    id: 1,
    content:
      "Just learned how to say 'Thank you' in Darija: 'Shukran'! This app is amazing for picking up everyday phrases.",
    votes: 15,
    tags: ["Phrases", "Learning"],
    user: {
      name: "Sarah Johnson",
      avatar: "https://example.com/avatars/sarah.jpg",
      bio: "English teacher exploring Moroccan culture",
      role: "Learner",
    },
    date: "2024-07-01T14:30:00Z",
    commentsNumber: 3,
  },
  {
    id: 7,
    content:
      "Quick tip: 'Inshallah' is used a lot in daily Darija conversations. It means 'God willing' or 'hopefully'.",
    votes: 25,
    tags: ["Vocabulary", "Culture"],
    user: {
      name: "Hassan Mansouri",
      avatar: "https://example.com/avatars/hassan.jpg",
      bio: "Moroccan linguistics student",
      role: "contributor",
    },
    date: "2024-06-25T10:05:00Z",
    commentsNumber: 1,
  },
  {
    id: 3,
    content:
      "Anyone know how to say 'Where is the nearest cafe?' in Darija? Planning my trip to Marrakech!",
    votes: 5,
    tags: ["Question", "Travel"],
    user: {
      name: "Emma Wilson",
      avatar: "https://example.com/avatars/emma.jpg",
      bio: "Travel enthusiast and language lover",
      role: "Learner",
    },
    date: "2024-06-29T18:45:00Z",
    commentsNumber: 5,
  },
  {
    id: 4,
    content:
      "Just added 50 new food-related phrases to the database. Enjoy learning about Moroccan cuisine!",
    votes: 22,
    tags: ["Update", "Food"],
    user: {
      name: "Fatima Zahra",
      avatar: "https://example.com/avatars/fatima.jpg",
      bio: "Moroccan chef and language enthusiast",
      role: "contributor",
    },
    date: "2024-06-28T11:20:00Z",
    commentsNumber: 4,
  },
  {
    id: 5,
    content:
      "The audio pronunciation feature is so helpful! I'm finally getting the hang of those tricky Darija sounds.",
    votes: 13,
    tags: ["Pronunciation", "Learning"],
    user: {
      name: "David Lee",
      avatar: "https://example.com/avatars/david.jpg",
      bio: "Aspiring polyglot",
      role: "Learner",
    },
    date: "2024-06-27T15:50:00Z",
    commentsNumber: 0,
  },
  {
    id: 6,
    content:
      "Suggestion: Can we add a section for Darija proverbs and their meanings? It would be great for cultural insight!",
    votes: 18,
    tags: ["Suggestion", "Proverbs"],
    user: {
      name: "Laila Bennani",
      avatar: "https://example.com/avatars/laila.jpg",
      bio: "Darija teacher and cultural expert",
      role: "contributor",
    },
    date: "2024-06-26T13:10:00Z",
    commentsNumber: 4,
  },

  {
    id: 8,
    content:
      "The difference between formal Arabic and Darija is fascinating. This app is really helping me navigate both!",
    votes: 9,
    tags: ["Observation", "Learning"],
    user: {
      name: "Anna Schmidt",
      avatar: "https://example.com/avatars/anna.jpg",
      bio: "Linguistics PhD student",
      role: "Learner",
    },
    date: "2024-06-24T16:40:00Z",
    commentsNumber: 16,
  },
  {
    id: 9,
    content:
      "Just updated the 'Transportation' category with 30 new entries. Navigating Morocco will be easier for travelers now!",
    votes: 14,
    tags: ["Update", "Travel"],
    user: {
      name: "Karim Idrissi",
      avatar: "https://example.com/avatars/karim.jpg",
      bio: "Tour guide and language enthusiast",
      role: "contributor",
    },
    date: "2024-06-23T08:55:00Z",
    commentsNumber: 9,
  },
  {
    id: 10,
    content:
      "Love the new feature that shows regional variations of phrases. Darija in Tangier vs Marrakech - so interesting!",
    votes: 20,
    tags: ["Dialect", "Learning"],
    user: {
      name: "Tom Parker",
      avatar: "https://example.com/avatars/tom.jpg",
      bio: "Expat living in Rabat",
      role: "Learner",
    },
    date: "2024-06-22T19:30:00Z",
    commentsNumber: 0,
  },
  {
    id: 2,
    content:
      "هاد الترجمة ماشي دقيقة. 'Marhaba' means 'Hello', not 'Goodbye'. Can we update this?",
    votes: 8,
    tags: ["Correction", "Vocabulary"],
    user: {
      name: "Youssef Alami",
      avatar: "https://example.com/avatars/youssef.jpg",
      bio: "Native Darija speaker from Casablanca",
      role: "contributor",
    },
    date: "2024-06-30T09:15:00Z",
    commentsNumber: 0,
  },
];

export const dummyPostComments = [
  {
    id: 101,
    content:
      "Great start, Sarah! 'Shukran' is used a lot. Try 'Baraka llahu fik' too for a more traditional Darija thanks!",
    user: {
      name: "Ahmed Benali",
    },
    date: "2024-07-01T15:00:00Z",
    votes: 26,
  },
  {
    id: 102,
    content: "This app is a game-changer for learning Darija! Keep it up!",
    user: {
      name: "Emma Thompson",
    },
    date: "2024-06-28T15:15:00Z",
    votes: 13,
  },
  {
    id: 103,
    content:
      "Pro tip: The pronunciation is more like 'shokran'. The 'u' sound is closer to 'o' in Darija.",
    user: {
      name: "Youssef Alaoui",
    },
    date: "2024-05-17T15:30:00Z",
    votes: 6,
  },
  {
    id: 104,
    content:
      "Nice! I just learned this too. It's amazing how a simple 'thank you' can brighten someone's day.",
    user: {
      name: "Lisa Chen",
    },
    date: "2024-05-01T16:00:00Z",
    votes: 3,
  },
  {
    id: 105,
    content:
      "Awesome Sarah! Next challenge: learn how to respond when someone thanks you!",
    user: {
      name: "Carlos Rodriguez",
    },
    date: "2024-04-01T16:30:00Z",
    votes: 0,
  },
];
