"""Add user_id to favorite table

Revision ID: 09a497c933fd
Revises: f7bb0aef9b96
Create Date: 2024-07-22 19:10:40.732756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09a497c933fd'
down_revision = 'f7bb0aef9b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
