"""Add source_language to history model

Revision ID: 2749e5c946fe
Revises: 2a3bee977a68
Create Date: 2024-07-19 17:14:40.944313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2749e5c946fe'
down_revision = '2a3bee977a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_language', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_column('source_language')

    # ### end Alembic commands ###
