"""Make shareable_link 15 chars long

Revision ID: 29ddfde6ba15
Revises: c97714e75a31
Create Date: 2024-08-13 21:11:57.027897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29ddfde6ba15'
down_revision = 'c97714e75a31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.alter_column('shareable_link',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.alter_column('shareable_link',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
