"""Update dictionary model

Revision ID: 4b03856c947f
Revises: 67ef37226f68
Create Date: 2024-07-13 12:48:49.483871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b03856c947f'
down_revision = '67ef37226f68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dictionary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arabic', sa.String(length=255), nullable=True))
        batch_op.alter_column('darija',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('english',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('noun', 'verb', 'adjective', 'adverb', 'preposition', 'pronoun'),
               type_=sa.Enum('noun', 'verb', 'adjective', 'adverb', 'preposition', 'pronoun '),
               nullable=False)
        batch_op.alter_column('source',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dictionary', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.Enum('noun', 'verb', 'adjective', 'adverb', 'preposition', 'pronoun '),
               type_=mysql.ENUM('noun', 'verb', 'adjective', 'adverb', 'preposition', 'pronoun'),
               nullable=True)
        batch_op.alter_column('english',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('darija',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('arabic')

    # ### end Alembic commands ###
