"""Add shareable_link to history model

Revision ID: 4c04bfedb70f
Revises: f72eb7458f09
Create Date: 2024-08-13 17:58:49.759692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c04bfedb70f'
down_revision = 'f72eb7458f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shareable_link', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_column('shareable_link')

    # ### end Alembic commands ###
