"""Link favorites to users

Revision ID: 4d73b591e24b
Revises: 09a497c933fd
Create Date: 2024-07-22 19:14:17.923767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d73b591e24b'
down_revision = '09a497c933fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('english', sa.Text(), nullable=False),
    sa.Column('darija', sa.Text(), nullable=False),
    sa.Column('arabic', sa.Text(), nullable=True),
    sa.Column('word_type', sa.String(length=128), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('english', mysql.TEXT(), nullable=False),
    sa.Column('darija', mysql.TEXT(), nullable=False),
    sa.Column('arabic', mysql.TEXT(), nullable=True),
    sa.Column('word_type', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('favorites')
    # ### end Alembic commands ###
