"""Change dictionary type/category columns

Revision ID: 6227344a9eae
Revises: e566576687b3
Create Date: 2024-07-14 11:24:31.867230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6227344a9eae'
down_revision = 'e566576687b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dictionary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('word_type', sa.String(length=255), nullable=True))
        batch_op.alter_column('category',
               existing_type=mysql.ENUM('family', 'education', 'clothes', 'food', 'colors', 'sports', 'numbers', 'health', 'animals', 'places', 'religion', 'time', 'emotions', 'nature', 'objects', 'planets', 'professions', 'body', 'plants'),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dictionary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.ENUM('noun', 'verb', 'adjective', 'adverb', 'preposition', 'pronoun'), nullable=False))
        batch_op.alter_column('category',
               existing_type=sa.String(length=255),
               type_=mysql.ENUM('family', 'education', 'clothes', 'food', 'colors', 'sports', 'numbers', 'health', 'animals', 'places', 'religion', 'time', 'emotions', 'nature', 'objects', 'planets', 'professions', 'body', 'plants'),
               existing_nullable=True)
        batch_op.drop_column('word_type')

    # ### end Alembic commands ###
