"""Initial migration

Revision ID: 67ef37226f68
Revises: 
Create Date: 2024-07-12 18:34:14.550743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ef37226f68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('darija', sa.String(length=80), nullable=False),
    sa.Column('english', sa.String(length=80), nullable=False),
    sa.Column('type', sa.Enum('noun', 'verb', 'adjective', 'adverb', 'preposition', 'pronoun '), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('views_number', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dictionary')
    # ### end Alembic commands ###
