"""edit source column to data_source

Revision ID: 6d3fa448a697
Revises: f2dd4964a693
Create Date: 2024-07-19 15:45:10.161861

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "6d3fa448a697"
down_revision = "f2dd4964a693"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dictionary", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("data_source", sa.String(length=255), nullable=True)
        )
        batch_op.drop_column("source")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dictionary", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("source", mysql.VARCHAR(length=255), nullable=True)
        )
        batch_op.drop_column("data_source")

    # ### end Alembic commands ###
