"""Add arabic column to History model

Revision ID: 8f05323b8062
Revises: b8fcd82780d3
Create Date: 2025-01-30 14:50:55.423217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f05323b8062'
down_revision = 'b8fcd82780d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arabic', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_column('arabic')

    # ### end Alembic commands ###
