"""Add dictionary_id field to favorite

Revision ID: 9b7d05f29c03
Revises: 4d73b591e24b
Create Date: 2024-07-23 18:55:52.110421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b7d05f29c03'
down_revision = '4d73b591e24b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dictionary_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_column('dictionary_id')

    # ### end Alembic commands ###
