"""Update dictionary add family_id column

Revision ID: a1804956e896
Revises: 4b03856c947f
Create Date: 2024-07-13 13:44:32.383170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1804956e896'
down_revision = '4b03856c947f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dictionary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', sa.Integer(), nullable=True))
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('noun', 'verb', 'adjective', 'adverb', 'preposition', 'pronoun'),
               type_=sa.Enum('noun', 'verb', 'adjective', 'adverb', 'preposition', 'pronoun '),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dictionary', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('noun', 'verb', 'adjective', 'adverb', 'preposition', 'pronoun '),
               type_=mysql.ENUM('noun', 'verb', 'adjective', 'adverb', 'preposition', 'pronoun'),
               existing_nullable=False)
        batch_op.drop_column('family_id')

    # ### end Alembic commands ###
