"""Add deleted column to history model

Revision ID: d3752b408cd2
Revises: 2749e5c946fe
Create Date: 2024-07-20 18:08:57.557922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3752b408cd2'
down_revision = '2749e5c946fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=False))
        batch_op.alter_column('source_language',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.alter_column('source_language',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
