"""Update dictionary change category column name

Revision ID: e566576687b3
Revises: c966e70b4760
Create Date: 2024-07-13 15:38:40.145126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e566576687b3'
down_revision = 'c966e70b4760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dictionary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.drop_column('family_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dictionary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
